const allIcons = {
  chevronLeft: '/icons/chevron-left.svg',
  homeActive: '/icons/home-active.svg',
  homeInactive: '/icons/home-inactive.svg',
  calendarActive: '/icons/calendar-active.svg',
  calendarInactive: '/icons/calendar-inactive.svg',
  userActive: '/icons/user-active.svg',
  userInactive: '/icons/user-inactive.svg',
  bellActive: '/icons/bell-active.svg',
  bellInactive: '/icons/bell-inactive.svg',
  timoTitle: '/icons/timo-title.svg',
  fire: '/icons/fire.svg',
  calendarDayPastN: '/icons/calendar-day-past-n.svg',
  calendarDayPastP: '/icons/calendar-day-past-p.svg',
  calendarDayPresentH: '/icons/calendar-day-present-h.svg',
  calendarDayPresentF: '/icons/calendar-day-present-f.svg',
  calendarDayFuture: '/icons/calendar-day-future.svg',
  calendarDaySlate: '/icons/calendar-day-slate.svg',
  calendarDayOutline: '/icons/calendar-day-outline.svg',
  close: '/icons/close.svg',
  alert: '/icons/alert-fill.svg',
  checkCircle: '/icons/check-circle-fill.svg',
  check: '/icons/check-fill.svg',
  groupsActive: '/icons/groups-active.svg',
  groupsInactive: '/icons/groups-inactive.svg',
  starFilled: '/icons/star-filled.svg',
  starOutline: '/icons/star-outline.svg',
  statisticsActive: '/icons/statistics-active.svg',
  statisticsInactive: '/icons/statistics-inactive.svg',
} as const;

export default allIcons;
